NAME = test

src	=	check_flor_ceiling_colour.c check_map_surrounded.c input_prep.c main.c

all:
	gcc $(src) -o $(NAME) ../../libft/libft.a ../../get_next_line/get_next_line.a

clean:
	rm $(NAME)

re: clean all
